# Copyright (C) 2022 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/austin/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/austin/proprietary/etc/.tp/thermal.policy.conf:system/etc/.tp/thermal.policy.conf \
    vendor/amazon/austin/proprietary/lib/libasp.so:system/lib/libasp.so \
    vendor/amazon/austin/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/amazon/austin/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/amazon/austin/proprietary/lib/libcjson.so:system/lib/libcjson.so \
    vendor/amazon/austin/proprietary/vendor/etc/audio-algorithms/AFE.cfg:system/vendor/etc/audio-algorithms/AFE.cfg \
    vendor/amazon/austin/proprietary/vendor/etc/audio-algorithms/EQ_2048.cfg:system/vendor/etc/audio-algorithms/EQ_2048.cfg \
    vendor/amazon/austin/proprietary/vendor/etc/audio-algorithms/MBCL.cfg:system/vendor/etc/audio-algorithms/MBCL.cfg \
    vendor/amazon/austin/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank.cfg:system/vendor/etc/audio-algorithms/coefs_FilterBank.cfg \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/anlg_dock_headset.csv:system/vendor/smartvolume/austin/anlg_dock_headset.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/aux_digital.csv:system/vendor/smartvolume/austin/aux_digital.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/bt_a2dp.csv:system/vendor/smartvolume/austin/bt_a2dp.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/bt_a2dp_headphones.csv:system/vendor/smartvolume/austin/bt_a2dp_headphones.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/bt_a2dp_speaker.csv:system/vendor/smartvolume/austin/bt_a2dp_speaker.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/bt_sco.csv:system/vendor/smartvolume/austin/bt_sco.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/bt_sco_carkit.csv:system/vendor/smartvolume/austin/bt_sco_carkit.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/bt_sco_headset.csv:system/vendor/smartvolume/austin/bt_sco_headset.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/default.csv:system/vendor/smartvolume/austin/default.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/dgtl_dock_headeset.csv:system/vendor/smartvolume/austin/dgtl_dock_headeset.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/speaker.csv:system/vendor/smartvolume/austin/speaker.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/wired_headphone.csv:system/vendor/smartvolume/austin/wired_headphone.csv \
    vendor/amazon/austin/proprietary/vendor/smartvolume/austin/wired_headset.csv:system/vendor/smartvolume/austin/wired_headset.csv
